version: '3.8'
services:
  db:
    image: mongo
    ports:
      - '3135:27017'
    volumes:
      - cardcraftdb:/data/db

  sonar:
    image: sonarqube:latest
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - 9009:9000
volumes:
  cardcraftdb:
