[tool.poetry]
name = "cardgames"
version = "0.1.0"
description = ""
authors = ["Luka L <licina.luka@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pysonar-scanner = "0.2.0.520"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
